# GitHub Pages Jekyll Configuration
title: "AI-Era Developer Career Framework"
description: "A comprehensive professional development system for software engineers navigating the AI revolution"
url: "https://CodeTreatise.github.io"
baseurl: "/nextGenJob"

# Theme
theme: minima
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .git/
  - .gitignore
